changed to 2nd version of fadecut

diff --git a/fadecut b/fadecut
--- a/fadecut
+++ b/fadecut
@@ -3,8 +3,42 @@ FILES=*.mp3
 OUTPUTDIR=new
 ERRORDIR=error
 ENQUEUE=0
-GENRE="Chillout"
-COMMENT="ANTENNE BAYERN Chillout"
+
+E_NOARGS=65
+
+if [ $# -eq 0 ] 
+then
+  echo "Usage: `basename $0` pop|chillout" >&2
+  # Error message to stderr.
+  exit $E_NOARGS
+  # Returns 65 as exit status of script (error code).
+fi  
+
+if [ "$1" == "pop" ] 
+then
+  GENRE="Pop"
+  COMMENT="Radio Swiss Pop"
+
+  #all values in seconds:
+  TRIM_BEGIN=7
+  TRIM_END=6
+  FADE_IN=1
+  FADE_OUT=2
+fi
+
+if [ "$1" == "chillout" ] 
+then
+  GENRE="Chillout"
+  COMMENT="ANTENNE BAYERN Chillout"
+
+  #all values in seconds:
+  TRIM_BEGIN=5
+  TRIM_END=7
+  FADE_IN=2
+  FADE_OUT=5
+fi
+
+
 
 if [ ! -d "$OUTPUTDIR" ]; then
   mkdir -p "$OUTPUTDIR"
@@ -18,14 +52,11 @@ for F in $FILES
 do
   echo "Processing $F ..."
   LENGTH=`soxi -D "$F" | sed -e 's/\..*//'` 
-  let TRIMLENGTH=$((LENGTH-10))
-  let FADESTART=$((LENGTH-15))
+  let TRIMLENGTH=$((LENGTH-TRIM_BEGIN-TRIM_END))
+  let FADE_OUT_START=$((TRIMLENGTH-FADE_OUT))
   ARTIST=`echo $F | sed -e 's/ -.*//'`
   TITLE=`echo $F | sed -e 's/^.* - //' | sed -e 's/.mp3//'`
-  nice -15 sox -V1 "$F" -t wav - trim 5 $TRIMLENGTH fade t 2 $FADESTART 5 | nice -15 lame --quiet --add-id3v2 --ta "$ARTIST" --tt "$TITLE" --tg "$GENRE" --tc "$COMMENT" - "$OUTPUTDIR"/"$F" 
-  #                                   |      |             |            |
-  # cut 5 secs at beginning and end <-+------+             |            |
-  # fade 2 secs in and 5 secs out   <----------------------+------------+
+  nice -15 sox -V1 "$F" -t wav - trim $TRIM_BEGIN $TRIMLENGTH fade t $FADE_IN $FADE_OUT_START $FADE_OUT | nice -15 lame --quiet --add-id3v2 --ta "$ARTIST" --tt "$TITLE" --tg "$GENRE" --tc "$COMMENT" - "$OUTPUTDIR"/"$F" 
   if [ "$?" -eq "0" ]; then
     rm "$F"
   else
